// 公共
export const baseServer = ''
export const baseUrl = ''
export const authUrl = ''
export const serviceUrl = ''
export const dataUrl = ''
export const eduBureauEmpsUploadUrl = ''
export const teachersUploadUrl = ''
export const studentUploadUrl = ''
export const fileUrl = ''
